### ISSUE TITLE
make theia_e3

### ISSUE THREAD

**Issue by alston2506** [crimson-unicorn/core#1]
I run "make theia_e3", there is a command 
"cd data && git clone git@github.com:michael-hahn/theia-e3.git" in the make file, 
but the repository ”git@github.com:michael-hahn/theia-e3.git“ does not exist？

**Comment by michael-hahn** [comment]
My apologies. The repo was accidentally set to be private. You should be able to pull it now. Thank you.

**Comment by alston2506** [comment]
Sorry，this command “git clone git@github.com:michael-hahn/theia-e3.git” does still not work ，and the repo still empty。

**Comment by michael-hahn** [comment]
Please try again now. For some reason, my previous attempt failed.

**Comment by alston2506** [comment]
OK,Thx, it works。
By the way, other repo used in core/MakeFile to download the dataset such as fivedirections_e3, clearscope_e3, camflow_apt, etc. Could you please make them public ?

Below are these commands: 

git clone git@github.com:michael-hahn/cadets-e3.git
git clone git@github.com:michael-hahn/theia-e3.git
git clone git@github.com:michael-hahn/camflow-apt-new-label.git camflow-apt
git clone git@github.com:michael-hahn/camflow-apt-raw.git camflow-apt
git clone git@github.com:michael-hahn/fivedirections-e3.git
git clone git@github.com:michael-hahn/clearscope-e3.git
git clone git@github.com:michael-hahn/spade-wget-apt.git
git clone git@github.com:michael-hahn/shellshock-apt-new-label.git shellshock-apt
git clone git@github.com:crimson-unicorn/camflow-extended-dataset.git

**Comment by michael-hahn** [comment]
The following datasets are now made public and they should be the ones that we use in our evaluation in the paper: 
git clone git@github.com:michael-hahn/cadets-e3.git
git clone git@github.com:michael-hahn/theia-e3.git
git clone git@github.com:michael-hahn/fivedirections-e3.git
git clone git@github.com:michael-hahn/clearscope-e3.git

Please use caution when using the following datasets (they are made public now) as they are mainly used internally for our own uses:
git clone git@github.com:michael-hahn/camflow-apt-new-label.git camflow-apt
git clone git@github.com:michael-hahn/camflow-apt-raw.git camflow-apt
git clone git@github.com:michael-hahn/spade-wget-apt.git
git clone git@github.com:michael-hahn/shellshock-apt-new-label.git shellshock-apt

The repository below is already available publicly:
git clone git@github.com:crimson-unicorn/camflow-extended-dataset.git

Thanks!

**Comment by alston2506** [comment]
Thank you very much !!

**Comment by alston2506** [comment]
When I git clone the dataset，an error occurred：

Error downloading object: attack/theia-e3-official-1r.gz.tar (f3cea53): Smudge error: Error downloading attack/theia-e3-official-1r.gz.tar (f3cea53a3e63def8f8d614c42771fc1a5a6e02681615006d91a557e91f4f51d2): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by michael-hahn** [comment]
Thanks for reporting this to us. We will move those repositories to a paid GitHub account that has more data packs! We will let you know when it is done!

**Comment by michael-hahn** [comment]
The following repositories have been relocated to enable LFS:
git@github.com:margoseltzer/theia-e3.git
git@github.com:margoseltzer/fivedirections-e3.git
git@github.com:margoseltzer/clearscope-e3.git
git@github.com:margoseltzer/camflow-apt-new-label.git
git@github.com:margoseltzer/camflow-apt-raw.git
git@github.com:margoseltzer/spade-wget-apt.git
git@github.com:margoseltzer/shellshock-apt-new-label.git

The following repository is still being transferred, but check later:
git@github.com:margoseltzer/cadets-e3.git

**Comment by lizitong67** [comment]
really appreciate
