### ISSUE TITLE
Cannot clone cadets-e3

### ISSUE THREAD

**Issue by HermitSun** [crimson-unicorn/core#4]
When I clone cadets-e3 from [michael-hahn/cadets-e3](https://github.com/michael-hahn/cadets-e3), an error occurred: 
```
Smudge error: Error downloading attack/cadets-e3-official-0.gz.tar 
batch response: This repository is over its data quota. 
Account responsible for LFS bandwidth should purchase more data packs to restore access.
```
It seems that there is no space for this repo in the account. 

I also followed the instructions here https://github.com/crimson-unicorn/core/issues/1#issuecomment-616541264,  but margoseltzer/cadets-e3 is missing.

So, how could I clone cadets-e3?

**Comment by michael-hahn** [comment]
Sorry that we have not had the chance to resolve the issue. However, cadets dataset is publicly available somewhere else as well: https://drive.google.com/drive/folders/179uDuz62Aw61Ehft6MoJCpPeBEz16VFy

**Comment by HermitSun** [comment]
OK, I will try. 
Thank you for your excellent work! 🚀
